using DiagnosticFlashTool.Core.Algorithms;

namespace DiagnosticFlashTool.Infrastructure.Security;

/// <summary>
/// Seed&amp;Key registry adapter backed by a vendor DLL through SeedKeyWorker.
/// </summary>
public sealed class DllSeedKeyAlgorithm : ISeedKeyAlgorithm
{
    private readonly SeedKeyDllOptions _options;
    private readonly SeedKeyWorkerClient _workerClient;

    public DllSeedKeyAlgorithm(
        SeedKeyDllOptions options,
        SeedKeyWorkerClient? workerClient = null)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
        _workerClient = workerClient ?? new SeedKeyWorkerClient();
    }

    public string Name => _options.AlgorithmName;

    public async ValueTask<byte[]> ComputeKeyAsync(
        byte[] seed,
        IReadOnlyList<string> parameters,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(seed);
        ArgumentNullException.ThrowIfNull(parameters);

        // Awaited rather than blocked: the key is generated by a separate worker
        // process, so waiting synchronously would pin a thread and make a cancel
        // request unable to reach the worker.
        return await _workerClient.ComputeKeyAsync(_options, seed, cancellationToken).ConfigureAwait(false);
    }
}
