using DiagnosticFlashTool.Core.Algorithms;
using DiagnosticFlashTool.Core.Configuration;
using DiagnosticFlashTool.Core.Diagnostics;
using DiagnosticFlashTool.Core.Firmware;
using DiagnosticFlashTool.Core.Util;

namespace DiagnosticFlashTool.Core.Flashing;

public sealed class FlashFlowExecutor
{
    private readonly UdsClient _udsClient;
    private readonly SeedKeyAlgorithmRegistry _seedKeyAlgorithms;
    private byte[] _lastSeed = [];

    public FlashFlowExecutor(UdsClient udsClient, SeedKeyAlgorithmRegistry? seedKeyAlgorithms = null)
    {
        _udsClient = udsClient;
        _seedKeyAlgorithms = seedKeyAlgorithms ?? new SeedKeyAlgorithmRegistry();
    }

    public async Task<FlashResult> ExecuteAsync(
        BootConfig bootConfig,
        ProjectConfigEntry project,
        FirmwareSet firmwareSet,
        IProgress<FlashProgress>? progress,
        Action<string>? log,
        CancellationToken cancellationToken)
    {
        var logs = new List<string>();
        void WriteLog(string message)
        {
            var line = $"[{DateTime.Now:HH:mm:ss}] {message}";
            logs.Add(line);
            log?.Invoke(line);
        }

        try
        {
            if (bootConfig.Flow.Count == 0)
            {
                throw new InvalidOperationException($"BOOT config has no flow steps: {bootConfig.Name}");
            }

            WriteLog($"Start flash: project={project.ProjectName}, boot={bootConfig.Name}");

            for (var index = 0; index < bootConfig.Flow.Count; index++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var step = bootConfig.Flow[index];
                var percent = (int)Math.Round(index * 100.0 / bootConfig.Flow.Count);
                progress?.Report(new FlashProgress(percent, $"Step {step.Id}: {step.Name}"));
                WriteLog($"Step {step.Id}: {step.Name}");

                if (string.Equals(step.StepType, "DownloadDriver", StringComparison.OrdinalIgnoreCase))
                {
                    await DownloadImageAsync(firmwareSet.Driver, step, FirmwareImageKind.Driver, WriteLog, progress, cancellationToken).ConfigureAwait(false);
                }
                else if (string.Equals(step.StepType, "DownloadApplication", StringComparison.OrdinalIgnoreCase))
                {
                    await DownloadImageAsync(firmwareSet.Application, step, FirmwareImageKind.Application, WriteLog, progress, cancellationToken).ConfigureAwait(false);
                }
                else
                {
                    await ExecuteUdsStepAsync(step, WriteLog, cancellationToken).ConfigureAwait(false);
                }
            }

            progress?.Report(new FlashProgress(100, "Flash completed"));
            WriteLog("Flash completed.");
            return new FlashResult { Success = true, UserMessage = "刷写完成", LogMessages = logs };
        }
        catch (Exception ex)
        {
            WriteLog($"ERROR: {ex.Message}");
            return new FlashResult { Success = false, UserMessage = ex.Message, LogMessages = logs };
        }
    }

    private async Task ExecuteUdsStepAsync(FlashStepConfig step, Action<string> log, CancellationToken cancellationToken)
    {
        if (!HexUtil.TryParseByte(step.Service, out var serviceId))
        {
            log("Skip non-UDS step without service.");
            return;
        }

        var parameters = new List<byte>();
        if (HexUtil.TryParseByte(step.SubService, out var subService))
        {
            parameters.Add(subService);
        }

        parameters.AddRange(step.Extend.SelectMany(HexUtil.ParseBytes));

        if (serviceId == 0x27 && subService % 2 == 0 && !string.IsNullOrWhiteSpace(step.SecurityAlgorithm))
        {
            var algorithm = _seedKeyAlgorithms.Resolve(step.SecurityAlgorithm);
            var key = algorithm.ComputeKey(_lastSeed, step.AlgorithmParams.ToList());
            parameters.AddRange(key);
            log($"Security key generated by {algorithm.Name}, seed={HexUtil.ToHex(_lastSeed)}, key={HexUtil.ToHex(key)}");
        }

        var response = await _udsClient.SendAsync(
            serviceId,
            parameters,
            ParseAddressing(step.AddressingMode),
            TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.TimeoutMs, 1500)),
            TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.PendingTimeoutMs, 30_000)),
            cancellationToken).ConfigureAwait(false);

        response.EnsurePositive();
        log($"RX {response}");

        if (serviceId == 0x27 && response.Payload.Length > 2 && response.Payload[0] == 0x67 && response.Payload[1] % 2 == 1)
        {
            _lastSeed = response.Payload.Skip(2).ToArray();
        }
    }

    private async Task DownloadImageAsync(
        FirmwareImage? image,
        FlashStepConfig step,
        FirmwareImageKind kind,
        Action<string> log,
        IProgress<FlashProgress>? progress,
        CancellationToken cancellationToken)
    {
        if (image is null || image.Length == 0)
        {
            log($"{kind} firmware not configured, skip download step.");
            return;
        }

        foreach (var block in image.Blocks)
        {
            await RequestDownloadAsync(block.Address, block.Data.Length, step, cancellationToken).ConfigureAwait(false);

            const int payloadSize = 0xF0;
            var blockCounter = 1;
            for (var offset = 0; offset < block.Data.Length; offset += payloadSize)
            {
                var count = Math.Min(payloadSize, block.Data.Length - offset);
                var payload = new byte[2 + count];
                payload[0] = 0x36;
                payload[1] = (byte)(blockCounter & 0xFF);
                Buffer.BlockCopy(block.Data, offset, payload, 2, count);

                var response = await _udsClient.SendRawAsync(
                    payload,
                    ParseAddressing(step.AddressingMode),
                    TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.TimeoutMs, 1500)),
                    TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.PendingTimeoutMs, 30_000)),
                    cancellationToken).ConfigureAwait(false);
                response.EnsurePositive();

                blockCounter = (blockCounter + 1) & 0xFF;
                var percentWithinImage = (int)Math.Round((offset + count) * 100.0 / block.Data.Length);
                progress?.Report(new FlashProgress(percentWithinImage, $"{kind} download {percentWithinImage}%"));
            }

            var exitResponse = await _udsClient.SendRawAsync(
                [0x37],
                ParseAddressing(step.AddressingMode),
                TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.TimeoutMs, 1500)),
                TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.PendingTimeoutMs, 30_000)),
                cancellationToken).ConfigureAwait(false);
            exitResponse.EnsurePositive();
            log($"{kind} block downloaded: address=0x{block.Address:X8}, length={block.Data.Length}");
        }
    }

    private async Task RequestDownloadAsync(uint address, int length, FlashStepConfig step, CancellationToken cancellationToken)
    {
        var request = new byte[11];
        request[0] = 0x34;
        request[1] = 0x00;
        request[2] = 0x44;
        WriteUInt32BigEndian(request.AsSpan(3, 4), address);
        WriteUInt32BigEndian(request.AsSpan(7, 4), (uint)length);

        var response = await _udsClient.SendRawAsync(
            request,
            ParseAddressing(step.AddressingMode),
            TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.TimeoutMs, 1500)),
            TimeSpan.FromMilliseconds(HexUtil.ParseInt(step.PendingTimeoutMs, 30_000)),
            cancellationToken).ConfigureAwait(false);
        response.EnsurePositive();
    }

    private static void WriteUInt32BigEndian(Span<byte> span, uint value)
    {
        span[0] = (byte)((value >> 24) & 0xFF);
        span[1] = (byte)((value >> 16) & 0xFF);
        span[2] = (byte)((value >> 8) & 0xFF);
        span[3] = (byte)(value & 0xFF);
    }

    private static UdsAddressing ParseAddressing(string? value)
    {
        return string.Equals(value, "functional", StringComparison.OrdinalIgnoreCase)
            ? UdsAddressing.Functional
            : UdsAddressing.Physical;
    }
}
